# Generated by Django 5.2.16 on 2026-07-24 09:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baci_code', models.CharField(max_length=8, unique=True)),
                ('m49_code', models.CharField(max_length=3, unique=True)),
                ('iso2', models.CharField(max_length=2, unique=True)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code', 'version'),
                'constraints': [models.UniqueConstraint(fields=('code', 'version'), name='unique_classification_version')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('level', models.PositiveSmallIntegerField(choices=[(2, 'HS2'), (4, 'HS4'), (6, 'HS6')], validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(6)])),
                ('parent_code', models.CharField(blank=True, max_length=6)),
                ('name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.productclassification')),
            ],
            options={
                'ordering': ('code',),
                'constraints': [models.UniqueConstraint(fields=('classification', 'code'), name='unique_product_classification_code'), models.CheckConstraint(condition=models.Q(('level__in', (2, 4, 6))), name='supported_product_level')],
            },
        ),
    ]
