# Generated by Django 5.2.16 on 2026-07-24 10:09

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('iso2'), name='unique_country_iso2_ci'),
        ),
        migrations.AddConstraint(
            model_name='country',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('iso3'), name='unique_country_iso3_ci'),
        ),
    ]
