# Generated by Django 5.2.16 on 2026-07-24 10:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_country_unique_country_iso2_ci_and_more'),
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualTradeFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('hs6_code', models.CharField(max_length=6)),
                ('hs4_code', models.CharField(max_length=4)),
                ('hs2_code', models.CharField(max_length=2)),
                ('trade_value_usd', models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('quantity_tons', models.DecimalField(blank=True, decimal_places=3, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('unit_value_usd_per_ton', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.productclassification')),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_flows', to='datasets.datasetversion')),
                ('exporter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exported_trade_flows', to='catalog.country')),
                ('importer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_trade_flows', to='catalog.country')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.datasource')),
            ],
            options={
                'ordering': ('year', 'exporter_id', 'importer_id', 'hs6_code'),
                'indexes': [models.Index(fields=['dataset_version', 'year'], name='trade_dataset_year_idx'), models.Index(fields=['exporter', 'year'], name='trade_exporter_year_idx'), models.Index(fields=['importer', 'year'], name='trade_importer_year_idx'), models.Index(fields=['hs2_code', 'year'], name='trade_hs2_year_idx'), models.Index(fields=['hs6_code', 'year'], name='trade_hs6_year_idx')],
                'constraints': [models.UniqueConstraint(fields=('dataset_version', 'year', 'exporter', 'importer', 'hs6_code'), name='unique_annual_trade_flow')],
            },
        ),
    ]
