# Generated by Django 5.2.16 on 2026-07-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_country_unique_country_iso2_ci_and_more'),
        ('datasets', '0001_initial'),
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='annualtradeflow',
            index=models.Index(fields=['dataset_version', 'importer', 'hs2_code', 'year'], name='trade_import_hs2_year_idx'),
        ),
        migrations.AddIndex(
            model_name='annualtradeflow',
            index=models.Index(fields=['dataset_version', 'exporter', 'hs2_code', 'year'], name='trade_export_hs2_year_idx'),
        ),
    ]
