# Generated by Django 5.2.16 on 2026-07-24 10:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(max_length=50)),
                ('task_type', models.CharField(max_length=50)),
                ('feature_schema_version', models.CharField(max_length=50)),
                ('training_period', models.JSONField(default=dict)),
                ('validation_period', models.JSONField(default=dict)),
                ('test_period', models.JSONField(default=dict)),
                ('algorithm', models.CharField(max_length=100)),
                ('hyperparameters', models.JSONField(default=dict)),
                ('metrics', models.JSONField(default=dict)),
                ('artifact_path', models.CharField(max_length=500)),
                ('checksum', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('training', 'Training'), ('candidate', 'Candidate'), ('active', 'Active'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='training', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('dataset_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='datasets.datasetversion')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['task_type', 'status'], name='model_task_status_idx'), models.Index(fields=['dataset_version', '-created_at'], name='model_dataset_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('task_type',), name='one_active_model_per_task'), models.UniqueConstraint(fields=('model_name', 'model_version'), name='unique_model_name_version')],
            },
        ),
    ]
